project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "ProPlotFits"
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Posts"
        href: posts.qmd
      - text: "Glossary"
        href: glossary.qmd
      - text: "About"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/gira-solo/proplotfits-website

  page-footer:
    left: "© 2026 ProPlotFits"
    right:
      - text: "About"
        href: about.qmd

format:
  html:
    theme:
      - cosmo
      - styles.css
    primary-color: "#174B8B"
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: false

execute:
  freeze: auto