---
title: "Royals vs. Braves · 2026-03-28"
description: "Velosalida y lanzángulo · Atlanta, GA"
date: "March 29, 2026"
categories: [royals, 2026, game-report, atlanta-braves]
author: "Peter Fortunato"
---

```{r}
#| fig-show: hold
#| results: hide
#| message: false
#| echo: false
#| warning: false

source(here::here("functions/game_report.R"))
plot_game_report("2026-03-28", "Braves", "ATL")
```

## El sweet spot

Salvy conectó el primer jonrón de 2026 para los Royals. We here at ProPlotFits didn't call it first, sin embargo, tenemos mucho orgullo in dedicating this blog and Royals Report Cards a él. También tuvo un hard hit out as well.

Jac Caglianone tuvo su primer breakout de 2026, con un doble dentro el sweet spot y un sencillo justo encima, just above, la media velosalida.

Desafortunatamente, the 8th-hitting DH, Dominic Smith, en su debut para los Braves, conectó el sweet spot más grande: a walk-off grand slam, después de ellos entraron the 9th-inning down 2-0.

## Debajo de la media

Bobby Witt, Jr. destacó otra vez. Jonathan India se queda frío, his bat stays cold, porque India vuelve a aparecer en la otra esquina equivocada del gráfico. Friday he had a soft-hit pop out, and Saturday a soft-hit ground out.

## Mirando adelante

Let's close out, cerramos. The Bullpen needs work. Michael Wacha lanzó un shutout sin importar, entonces, tenemos que asegurar su performancia fantástica.

------------------------------------------------------------------------

*Fuente: Baseball Savant · ProPlotFits*
