---
title: "A Tale of Two Hawks Part 1"
description: "Aquí es mi introducción"
date: last-modified
categories: [college-basketball, tutorial, kansas, miami-oh]
author: "Max Fortune"
---

There is only one team named the Jayhawks and that is the University of Kansas. They are my favorite college athletics team.

Solo hay uno equipo se llama los "Jayhawks", de la Universidad de Kansas. Es mi equipo favorito de atleticas univseritarias.

There is only one team named the RedHawks (with the "H" capitalized like that), and that is Miami University in Oxford, Ohio. I matriculated there as a freshman three months after, and a 50 minute drive from, the Harambe incident, and graduated with a Bachelor's and Master's during the Covid incident. Among other things I learned Spanish and Statistics.

Solo hay uno equipo se llama los "RedHawks" (con un "H" grande como así) de la Universidad de Miami de Ohio en Oxford. Matriculé allí como un freshman tres meses después, y cincuenta minutos de conducta desde, el incidende de Harambe, y gradué con un Bachelor's y Master's durante el incidente de Covid. En otras cosas, aprendí español y estadísticas.

It's been five years since my only graduation (because if Harambe wasn't enough Covid sent everybody home from just before my senior spring break). This is bilingual data journalism.

Hace cinco años que mi única graduación (porque Covid canceló las ceremonias de 2020). Por eso, bienveidos a periodísmo bilíngües de datos.

As of this post, Miami is for some reason undefeated and Kansas is a top-10 team with six losses. Kansas must have a lot of legacy fans, whereas CBS Sports' Bracketology [shows](https://www.cbssports.com/college-basketball/bracketology/) no other MAC school getting invited to the tournament.

A partir de hoy, Miami tiene ninguna derrota y Kansas está dentro el Top 10 con séis derrotas. Es cierto que Kansas tiene muchísimos fanaticos antiguos. Miami es la 

I never once attended a football or basketball game at Miami (I did see one hockey game). I like sports, but no one I went to school with was a fanatic about any sport. Apparently the RedHawks used to be super good at hockey and have accomplished alumni in the NHL, but by 2016 that hype seemed to have faded. To see Miami ranked 23 and not in football or hockey is quite astonishing, and it seems that Millett Hall is the place to be on game day despite being slated for demolition.

Not that the facility holds any sentimental value to me or anything, but rather the plans to replace Millett do worry me. My urban planning professor Dr. David Prytherch [outlined](https://www.miamistudent.net/article/2025/04/professor-against-new-arena-on-cook-field) the cost of developing a "Arena District" (which includes ) on top of an area that currently exists as a multi-use collection of turf fields known as "Cook Field". 

I for sure hope Miami doesn't use this new hype to justify building an arena and hotel right in the middle of campus. I could go on about how, from a transportation point of view, it's down right absurd. But you're here for predictive sports analytics, not expected transportation blunders.

Check-out a hypothetical match-up between the Jayhawks and RedHawks here.



